# Generated by Django 2.2.14 on 2021-07-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
