# Generated by Django 2.2.14 on 2021-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='item',
            name='size_large',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='size_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='size_small',
            field=models.IntegerField(default=0),
        ),
    ]
