# Generated by Django 2.2.14 on 2021-07-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210718_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size_extra_large',
            field=models.IntegerField(default=0),
        ),
    ]
