# Generated by Django 2.2.14 on 2021-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210718_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='selected_size',
            field=models.IntegerField(default=0),
        ),
    ]
