# Generated by Django 2.2.14 on 2021-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_selected_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='selected_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.IntegerField(default=0),
        ),
    ]
