# Generated by Django 2.2.14 on 2021-07-31 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
