# Generated by Django 2.2.14 on 2021-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='core.Image'),
        ),
    ]
